language: php

php:
  - 5.6

sudo: false

services:
  - mysql

cache:
   directories:
     - $HOME/.composer/cache/files

before_script:
  - phpenv config-rm xdebug.ini
  - mysql -e 'create database shopware;'

install:
  - echo {$TRAVIS_BUILD_DIR}
  - cd {$TRAVIS_BUILD_DIR}
  - git clone https://github.com/shopware/shopware.git
  - cd shopware
  - ant -f build/build.xml -Dapp.host=localhost -Ddb.user=travis -Ddb.host=127.0.0.1 -Ddb.name=shopware build-unit
  - cd custom/plugins
  - pwd
  - ls -ahl
  - ln -s {$TRAVIS_BUILD_DIR}/{$TRAVIS_REPO_SLUG} TestPlugin
  - cd TestPlugin
  - composer install
  - cd {$TRAVIS_BUILD_DIR}/shopware
  - php bin/console sw:plugin:refresh
  - php bin/console sw:plugin install TestPlugin
  - php bin/console sw:plugin activate TestPlugin

matrix:
  allow_failures:
    - php: nightly
