language: php

php:
  - 5.6

sudo: false

services:
  - mysql

cache:
   directories:
     - $HOME/.composer/cache/files

before_script:
  - phpenv config-rm xdebug.ini

install:
  - git clone https://github.com/shopware/shopware.git $HOME/shopware
  - ant -f $HOME/shopware/build/build.xml -Dapp.host=localhost -Ddb.user=travis -Ddb.host=127.0.0.1 -Ddb.name=shopware build-unit
  - mv $TRAVIS_BUILD_DIR $HOME/shopware/custom/plugins/TestPlugin
  - cd $HOME/shopware/custom/plugins/TestPlugin
  - composer install
  - cd /home/travis/build/shopware
  - php bin/console sw:plugin:refresh
  - php bin/console sw:plugin:install TestPlugin
  - php bin/console sw:plugin:activate TestPlugin
  - cd $HOME/shopware/custom/plugins/TestPlugin
  - composer test

matrix:
  allow_failures:
    - php: nightly
